name: S&P500ETL CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Debug file location
      - name: List all files
        run: ls -R

      # Step 5: Check for test.sh existence
      - name: Debug test.sh
        run: |
          if [ -f ./project/test.sh ]; then
            echo "test.sh exists and is ready to execute."
          else
            echo "test.sh not found."
            exit 1
          fi

      # Step 6: Ensure test.sh is executable
      - name: Ensure test.sh is executable
        run: chmod +x ./test.sh

      # Step 7: Run test.sh script
      - name: Run tests
        run: bash ./test.sh

      # Step 8: Upload logs (optional, for debugging on failure)
      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: etl-pipeline-logs
          path: ETLPipeline.log
