name: S&P500ETL CI

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Install dependencies, including Kaggle API
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install kaggle

      # Set up Kaggle API credentials
      - name: Set up Kaggle API credentials
        env:
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        run: |
          mkdir -p ~/.kaggle
          echo '{"username":"${KAGGLE_USERNAME}","key":"${KAGGLE_KEY}"}' > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      # Debug file location
      - name: List all files
        run: ls -R

      # Ensure test.sh is executable
      - name: Ensure test.sh is executable
        run: chmod +x ./project/test.sh

      # Run the test script
      - name: Run tests
        run: bash ./project/test.sh
