name: S&P500ETL CI

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: List all files to confirm file structure
      - name: List all files in repository
        run: ls -R

      # Step 3: Check if project/test.sh exists
      - name: Verify test.sh existence
        run: |
          if [ -f ./project/test.sh ]; then
            echo "test.sh exists in the project folder and is ready to execute."
          else
            echo "test.sh not found in the project folder."
            exit 1
          fi

      # Step 4: Ensure test.sh is executable
      - name: Ensure test.sh is executable
        run: chmod +x ./project/test.sh

      # Step 5: Run the test script
      - name: Run tests
        run: bash ./project/test.sh
